# Generated by Django 6.0.3 on 2026-06-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_create_default_pricing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(blank=True, help_text='Địa chỉ công ty', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='copyright_text',
            field=models.CharField(blank=True, help_text='Văn bản copyright', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='description',
            field=models.TextField(blank=True, help_text='Mô tả trang web'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Link Facebook'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_logo',
            field=models.ImageField(blank=True, help_text='Logo cho footer', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Link Instagram'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Link LinkedIn'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Giờ hoạt động (ví dụ: Mon-Fri: 9AM-6PM)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tagline',
            field=models.CharField(blank=True, help_text='Slogan/tagline của trang', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Link Twitter'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Link YouTube'),
        ),
    ]
