# Generated by Django 6.0.3 on 2026-06-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github',
        ),
    ]
