# Generated by Django 6.0.3 on 2026-06-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_project_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='featured',
            field=models.BooleanField(default=False, help_text='Đánh dấu ảnh này để hiển thị ở phần "Những bức ảnh nổi bật"'),
        ),
    ]
