# Generated by Django 6.0.3 on 2026-06-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_gallery_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('breadcrumb_title', models.CharField(blank=True, help_text='Tiêu đề nhỏ cho breadcrumb', max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True, help_text='Nội dung HTML của trang. Có thể dùng thẻ <p>, <strong>, <ul>, ...')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
