# Generated by Django 6.0.3 on 2026-06-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_create_default_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='Ghi lại những khoảnh khắc chạm đến trái tim bạn', max_length=300)),
                ('main_description', models.TextField(default='Chúng tôi tạo ra những hình ảnh và video đầy cảm xúc, chuyên nghiệp và mang đậm phong cách riêng.')),
                ('about_image', models.ImageField(blank=True, help_text='Ảnh chính trong phần Giới thiệu', null=True, upload_to='about/')),
                ('video_url', models.URLField(blank=True, help_text='Link video YouTube (ví dụ: https://www.youtube.com/watch?v=...)')),
            ],
            options={
                'verbose_name_plural': 'About Content',
            },
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_image', models.ImageField(help_text='Ảnh icon cho điểm nổi bật', upload_to='about/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'About Features',
                'ordering': ['order'],
            },
        ),
    ]
