# Generated by Django 6.0.3 on 2026-06-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_populate_about_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(help_text='Vị trí/chức vụ (ví dụ: Nhiếp ảnh gia, Đạo diễn)', max_length=100)),
                ('image', models.ImageField(help_text='Ảnh của thành viên', upload_to='team/')),
                ('facebook_url', models.URLField(blank=True, help_text='Link Facebook profile')),
                ('twitter_url', models.URLField(blank=True, help_text='Link Twitter profile')),
                ('youtube_url', models.URLField(blank=True, help_text='Link YouTube channel')),
                ('instagram_url', models.URLField(blank=True, help_text='Link Instagram profile')),
                ('order', models.IntegerField(default=0, help_text='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
    ]
