# Generated by Django 6.0.3 on 2026-06-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_populate_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_handle', models.CharField(blank=True, help_text='Tài khoản @ hoặc mô tả thêm', max_length=100)),
                ('quote', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='testimonial_description',
            field=models.TextField(blank=True, default='Đánh giá chân thực từ những khách hàng đã trải nghiệm dịch vụ của chúng tôi.', help_text='Mô tả nhỏ bên dưới tiêu đề testimonial'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='testimonial_title',
            field=models.CharField(blank=True, default='Khách hàng nói gì?', help_text='Tiêu đề phần testimonial trên trang About', max_length=200),
        ),
    ]
