# Generated by Django 6.0.3 on 2026-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_populate_default_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', '-percent']},
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='Mô tả ngắn cho kỹ năng này'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Tên icon Font Awesome (ví dụ: fa-camera) hoặc class CSS tùy chỉnh', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, help_text='Thứ tự hiển thị kỹ năng'),
        ),
    ]
