# Generated by Django 6.0.3 on 2026-06-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_skill_options_skill_description_skill_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, help_text='Hình ảnh đại diện cho kỹ năng', null=True, upload_to='skills/'),
        ),
    ]
