# Generated by Django 6.0.3 on 2026-06-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_add_footer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Ảnh hero hiển thị ở đầu trang chi tiết', null=True, upload_to='blogs/hero/'),
        ),
    ]
